package com.deepseek.studycircle.navigation

const val ROUTE_LOGIN="login"
const val ROUTE_REGISTER="register"
const val ROUTE_DASHBOARD="dashboard"
const val ROUTE_SPLASHSCREEN="splashscreen"
const val ROUTE_TUTORING="tutoring"
const val ROUTE_WHITEBOARD="whiteboard"
const val ROUTE_UPLOAD="upload"
const val ROUTE_GROUP="groups"
const val ROUTE_PROFILE="profile"
const val ROUTE_ACTIVITY="activity"
const val ROUTE_RESOURCE="resource/{resourceId}"
const val ROUTE_SETTINGS="settings"
const val ROUTE_KNOWLEDGE="knowledge"
const val ROUTE_SESSION="session"
const val ROUTE_TIMER="timer"
const val ROUTE_CREDITS="credits"
const val ROUTE_ABOUT="about"
